name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/apps/docker-demo
            git pull origin main

            docker build -t docker-demo .

            docker stop docker-demo || true
            docker rm docker-demo || true

            docker run -d \
              --name docker-demo \
              docker-demo